version: '3.1'

services:

    web:
       build: ./web
       environment:
         - APACHE_RUN_USER=www-data
       volumes:
         - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
       ports:
          - 8080:80
       working_dir: ${APP_PATH_CONTAINER}

    db:
      image: mariadb
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: pass
        MYSQL_DATABASE: ${MYSQL_DATABASE}
      volumes:
        - ${DB_PATH_HOST}:/var/lib/myaql

    adminer:
      image: adminer
      restart: always
      ports:
        - 6080:8080